# ============================
# Training Configuration
# ============================

# ==============================
# Dataset
# ==============================

image_train_dir: "/kaggle/input/datasets/borelgoudjou/scut-ctw1500/scut_data/scut_train"
ann_train_dir: "/kaggle/input/datasets/borelgoudjou/scut-ctw1500/scut_data/scut_train.txt"

image_val_dir: "/kaggle/input/datasets/borelgoudjou/scut-ctw1500/scut_data/scut_test"
ann_val_dir: "/kaggle/input/datasets/borelgoudjou/scut-ctw1500/scut_data/scut_test.txt"
num_sample: 100

# ==============================
# Model
# ==============================
model_name: "microsoft/trocr-small-printed"
max_length_pred: 128
num_beams : 2
show_number_parameter: True
checkpoint_path: ""
freeze_encoder: True
